language: swift
osx_image: xcode9.3
before_install:
  pod repo update
script:
  set -o pipefail &&
  xcodebuild -workspace OMGShop.xcworkspace -scheme "OMGShop" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8" test | xcpretty ;
